"""add booking constraint

Revision ID: 0b7dc85ebb76
Revises: 566ce5e78aa3
Create Date: 2023-10-01 18:27:08.099205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7dc85ebb76'
down_revision: Union[str, None] = '566ce5e78aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_diagnostic_location_time', 'bookings', ['diagnostic_id', 'location_id', 'booking_time'])
    op.create_unique_constraint('unique_doctor_location_time', 'bookings', ['doctor_id', 'location_id', 'booking_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_doctor_location_time', 'bookings', type_='unique')
    op.drop_constraint('unique_diagnostic_location_time', 'bookings', type_='unique')
    # ### end Alembic commands ###
