"""move specialties

Revision ID: 7b0bae0ba599
Revises: 5a5dafefde9b
Create Date: 2023-09-29 11:56:20.206721

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b0bae0ba599"
down_revision: Union[str, None] = "5a5dafefde9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text(
            "TRUNCATE TABLE doctors, diagnostic_locations, diagnostics, locations RESTART IDENTITY CASCADE;"
        )
    )
    op.create_table(
        "specialties",
        sa.Column("specialty_id", sa.Integer(), nullable=False),
        sa.Column("specialty_name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("specialty_id"),
    )
    op.add_column("doctors", sa.Column("specialty_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "doctors", "specialties", ["specialty_id"], ["specialty_id"]
    )
    op.drop_column("doctors", "specialty")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctors",
        sa.Column(
            "specialty", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "doctors", type_="foreignkey")
    op.drop_column("doctors", "specialty_id")
    op.drop_table("specialties")
    # ### end Alembic commands ###
