"""edit bookings

Revision ID: 54b5265d2e43
Revises: 0b7dc85ebb76
Create Date: 2023-10-01 19:16:39.146289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54b5265d2e43'
down_revision: Union[str, None] = '0b7dc85ebb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('bookings', 'booking_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    conn = op.get_bind()
    conn.execute(sa.text("TRUNCATE bookings RESTART IDENTITY CASCADE"))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
