"""add doctor about info

Revision ID: 80330b4aa722
Revises: 0e5cf4b909ff
Create Date: 2023-09-29 18:27:35.417696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80330b4aa722'
down_revision: Union[str, None] = '0e5cf4b909ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('experience', sa.TEXT(), nullable=True))
    op.add_column('doctors', sa.Column('certificates', sa.TEXT(), nullable=True))
    op.add_column('doctors', sa.Column('working_time', sa.TEXT(), nullable=True))
    op.add_column('doctors', sa.Column('services', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'working_time')
    op.drop_column('doctors', 'certificates')
    op.drop_column('doctors', 'experience')
    op.drop_column('doctors', 'services')
    # ### end Alembic commands ###
