"""add ondelete to slots

Revision ID: a6cf7fd5d39b
Revises: 3111b176081c
Create Date: 2023-09-30 15:08:04.061093

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6cf7fd5d39b"
down_revision: Union[str, None] = "3111b176081c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bookings_diagnostic_slot_id_fkey", "bookings", type_="foreignkey"
    )
    op.drop_constraint("bookings_doctor_slot_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(
        None,
        "bookings",
        "diagnostic_slots",
        ["diagnostic_slot_id"],
        ["diagnostic_slot_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "bookings",
        "doctor_slots",
        ["doctor_slot_id"],
        ["doctor_slot_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "diagnostic_slots_diagnostic_location_id_fkey",
        "diagnostic_slots",
        type_="foreignkey",
    )
    op.drop_constraint(
        "diagnostic_slots_slot_id_fkey", "diagnostic_slots", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "diagnostic_slots", "slots", ["slot_id"], ["slot_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "diagnostic_slots",
        "diagnostic_locations",
        ["diagnostic_location_id"],
        ["diagnostic_location_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("doctor_slots_slot_id_fkey", "doctor_slots", type_="foreignkey")
    op.drop_constraint(
        "doctor_slots_doctor_id_fkey", "doctor_slots", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "doctor_slots", "slots", ["slot_id"], ["slot_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "doctor_slots",
        "doctors",
        ["doctor_id"],
        ["doctor_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "doctor_slots_doctor_id_fkey",
        "doctor_slots",
        "doctors",
        ["doctor_id"],
        ["doctor_id"],
    )
    op.create_foreign_key(
        "doctor_slots_slot_id_fkey", "doctor_slots", "slots", ["slot_id"], ["slot_id"]
    )
    op.drop_constraint(None, "diagnostic_slots", type_="foreignkey")
    op.drop_constraint(None, "diagnostic_slots", type_="foreignkey")
    op.create_foreign_key(
        "diagnostic_slots_slot_id_fkey",
        "diagnostic_slots",
        "slots",
        ["slot_id"],
        ["slot_id"],
    )
    op.create_foreign_key(
        "diagnostic_slots_diagnostic_location_id_fkey",
        "diagnostic_slots",
        "diagnostic_locations",
        ["diagnostic_location_id"],
        ["diagnostic_location_id"],
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        "bookings_doctor_slot_id_fkey",
        "bookings",
        "doctor_slots",
        ["doctor_slot_id"],
        ["doctor_slot_id"],
    )
    op.create_foreign_key(
        "bookings_diagnostic_slot_id_fkey",
        "bookings",
        "diagnostic_slots",
        ["diagnostic_slot_id"],
        ["diagnostic_slot_id"],
    )
    op.drop_constraint(None, "doctor_slots", type_="foreignkey")
    op.drop_constraint(None, "doctor_slots", type_="foreignkey")
    # ### end Alembic commands ###
